# Generated by Django 3.2.16 on 2022-12-17 17:08

from django.db import migrations, models
import profit_and_loss.models


class Migration(migrations.Migration):

    dependencies = [
        ('profit_and_loss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentsAllData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('buyer_category', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, default=None, null=True)),
                ('value', models.FloatField(blank=True, default=None, null=True)),
                ('cost_price', models.FloatField(blank=True, default=None, null=True)),
                ('quantity', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='result',
            name='file',
            field=models.FileField(null=True, upload_to=profit_and_loss.models.PathRename('files/')),
        ),
    ]
